from enum import Enum


class ExplanationType(str, Enum):
    AI_EXPLANATION = "AI_EXPLANATION"
    SOURCE_EXPLANATION = "SOURCE_EXPLANATION"
    EVIDENCE_EXPLANATION = "EVIDENCE_EXPLANATION"
    SCORE_EXPLANATION = "SCORE_EXPLANATION"
    FINAL_SUMMARY = "FINAL_SUMMARY"
